version: "3.9"

services:
  go_api:
    build:
      context: .
      dockerfile: ./docker/go.dockerfile
    tty: true
    restart: always
    volumes:
      - type: bind
        source: ./app
        target: /go/src/app
    ports:
      - "4000:4000"
    command: reflex -r '(\.go$|go\.mod)' -s go run ./server.go

  mysql:
    build:
      context: .
      dockerfile: ./docker/mysql.dockerfile
    volumes:
       - db-data:/var/lib/mysql/data
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: develop-database
      MYSQL_USER: user
      MYSQL_PASSWORD: password

volumes:
  db-data:
