version: "3.9"

services:
  go_api:
    container_name: go_api
    build:
      context: .
      dockerfile: ./docker/go.dockerfile
    tty: true
    restart: always
    volumes:
      - type: bind
        source: .
        target: /go/src
    working_dir: /go/src/app
    ports:
      - "4000:4000"
    depends_on:
      - mysql
    command: sh ./start-api-server.sh

  mysql:
    container_name: go_mysql
    build:
      context: ./docker
      dockerfile: mysql.dockerfile
    volumes:
       - go_db_data:/var/lib/mysql
    restart: always
    tty: true
    ports:
      - "3306:3306"
    command: --character-set-server=utf8mb4 --explicit_defaults_for_timestamp=ON --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: develop_database
      MYSQL_USER: sample
      MYSQL_PASSWORD: password

volumes:
  go_db_data:
